pkgs:
  - origin: core
    name: hab
    channels:
      - dev
      - acceptance
      - stable
    targets:
      - x86_64-windows
      - x86_64-linux
  - origin: core
    name: hab-sup
    channels:
      - stable
    targets:
      - x86_64-windows
      - x86_64-linux
bldr_url: https://bldr.habitat.sh
refresh_interval_seconds: 30

