pkgs:
  - origin: sis
    name: chef-base
    channels:
      - qa
      - prod-group-1
      - prod-canary
    targets:
      - x86_64-windows
  - origin: sis
    name: multi
    channels:
      - qa
      - prod-group-1
    targets:
      - x86_64-windows
bldr_url: https://bldr.paneracloud.com
refresh_interval_seconds: 30
